// AFMAdapter.swift — Apple Foundation Models backend

import FoundationModels

/// On-device LLM adapter using Apple Foundation Models.
/// Each call creates a fresh LanguageModelSession (lightweight, not designed for reuse
/// across unrelated prompts).
public actor AFMAdapter: LLMAdapter {

  public init() {}

  // MARK: - Plain text generation

  public func generate(prompt: String, system: String?) async throws -> String {
    let model = SystemLanguageModel.default
    let session: LanguageModelSession
    if let system {
      session = LanguageModelSession(model: model, instructions: system)
    } else {
      session = LanguageModelSession(model: model)
    }

    do {
      let response = try await session.respond(to: prompt)
      return response.content
    } catch let error as LanguageModelSession.GenerationError {
      throw LLMError.from(error)
    }
  }

  // MARK: - Structured generation (AFM-specific)

  /// Generate structured output constrained by a @Generable type.
  /// This is the key advantage of AFM — guaranteed structural validity.
  public func generateStructured<T: GenerableContent>(
    prompt: String,
    system: String?,
    as type: T.Type
  ) async throws -> T {
    let model = SystemLanguageModel.default
    let session: LanguageModelSession
    if let system {
      session = LanguageModelSession(model: model, instructions: system)
    } else {
      session = LanguageModelSession(model: model)
    }

    do {
      let response = try await session.respond(to: prompt, generating: type)
      return response.content
    } catch let error as LanguageModelSession.GenerationError {
      throw LLMError.from(error)
    }
  }
}

// MARK: - Typealias for @Generable conformance requirement

/// Types that can be generated by AFM must conform to this.
public typealias GenerableContent = Generable & Sendable

// MARK: - Error mapping

extension LLMError {
  static func from(_ error: LanguageModelSession.GenerationError) -> LLMError {
    switch error {
    case .guardrailViolation:
      return .guardrailViolation
    case .assetsUnavailable:
      return .unavailable("On-device model assets not downloaded. Check Settings > Apple Intelligence.")
    default:
      return .generationFailed(error.localizedDescription)
    }
  }
}
